### ISSUE TITLE
Lagging Playback

### ISSUE THREAD

**Issue by Giggasus** [Darkside138/DiscordSoundboard#10]
Hi! Whenever I play a sound the playback seems very laggy and low quality. I have updated java and downloaded the bot again. I've also placed my mp3's in several locations but to no success. Any ideas? 

Thanks!

Update: I've also been encountering errors lately. This is the full error: 

[22:25:36] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[22:25:36] [Fatal] [JDA]: Encountered an exception:
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:101)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:177)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:65)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:551)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:298)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

Update 2: While messing around I encountered another error: 
[22:31:22] [Info] [ChatListener]: Attempting to play file: arms. Requested by Giggu.
[22:31:26] [Warning] [JDASocket]: Got an unexpected Json-parse error. Please redirect following message to the devs:
        JSONObject["endpoint"] not a string.
        VOICE_SERVER_UPDATE -> {"endpoint":null,"guild_id":"124649166700806144","token":null}

**Comment by safetyguy14** [comment]
I'm having the same issue: 
[20:40:20] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[20:40:20] [Fatal] [JDA]: Encountered an exception:
[20:40:20] [Fatal] [JDA]: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(Unknown Source)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:107)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:184)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleDefaultMessage(MessageReceivedHandler.java:94)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:50)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:596)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

**Comment by Darkside138** [comment]
Closing due to major new release. This is for the old version.
