### ISSUE TITLE
Something went wrong when looking up the track

### ISSUE THREAD

**Issue by Nacsis** [Darkside138/DiscordSoundboard#100]
Hi,
I got the bot working on my Ubuntu laptop. When I move the same files to my raspberry pi 3 b+ I can start the bot and it connects, but it doesn't play any sounds.
There is an Errormessage, but I don't know what to do. I already tried both JDAPlayer and musicPlayer.
Thanks,
Nacsis

``````pi@raspberrypi:~/soundboard $ java -jar DiscordSoundboard.jar 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/pi/soundboard/DiscordSoundboard.jar!/BOOT-INF/classes!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/pi/soundboard/DiscordSoundboard.jar!/BOOT-INF/lib/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::           (v2.2.2-beta)

2018-07-17 22:45:30.292  INFO 707 --- [           main] n.d.discordsoundboard.MainController     : Starting MainController v2.2.2-beta on raspberrypi with PID 707 (/home/pi/soundboard/DiscordSoundboard.jar started by pi in /home/pi/soundboard)
2018-07-17 22:45:30.307  INFO 707 --- [           main] n.d.discordsoundboard.MainController     : No active profile set, falling back to default profiles: default
2018-07-17 22:45:30.603  INFO 707 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@134b60d: startup date [Tue Jul 17 22:45:30 CEST 2018]; root of context hierarchy
2018-07-17 22:46:02.719  INFO 707 --- [           main] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode!
2018-07-17 22:46:08.802  INFO 707 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2018-07-17 22:46:10.778  INFO 707 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$53a0f6a6] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-07-17 22:46:14.643  INFO 707 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2018-07-17 22:46:14.713  INFO 707 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-07-17 22:46:14.719  INFO 707 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.20
2018-07-17 22:46:15.323  INFO 707 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-07-17 22:46:15.326  INFO 707 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 44736 ms
2018-07-17 22:46:17.131  INFO 707 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2018-07-17 22:46:17.169  INFO 707 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-07-17 22:46:17.172  INFO 707 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-07-17 22:46:17.174  INFO 707 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-07-17 22:46:17.176  INFO 707 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-07-17 22:46:22.935  INFO 707 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2018-07-17 22:46:41.094  INFO 707 --- [           main] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2018-07-17 22:46:44.835  INFO 707 --- [           main] net.dv8tion.jda.core.JDA                 : Login Successful!
2018-07-17 22:46:45.714  INFO 707 --- [inWS-ReadThread] n.d.jda.core.requests.WebSocketClient    : Connected to WebSocket
2018-07-17 22:46:47.460  INFO 707 --- [inWS-ReadThread] net.dv8tion.jda.core.JDA                 : Finished Loading!
2018-07-17 22:46:47.597  INFO 707 --- [           main] n.d.d.service.SoundPlayerImpl            : Loading from /home/pi/soundboard/sounds
2018-07-17 22:46:47.632  INFO 707 --- [           main] n.d.d.service.SoundPlayerImpl            : jeopardy
2018-07-17 22:46:48.803 ERROR 707 --- [inWS-ReadThread] n.d.jda.core.requests.WebSocketClient    : Encountered an Exception 

org.json.JSONException: JSONObject["d"] is not a JSONObject.
	at org.json.JSONObject.getJSONObject(JSONObject.java:641) ~[classes!/:2.2.2-beta]
	at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:940) ~[classes!/:2.2.2-beta]
	at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:661) ~[classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352) ~[classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260) [classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238) [classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963) [classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746) [classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [classes!/:2.2.2-beta]
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [classes!/:2.2.2-beta]

2018-07-17 22:46:49.466  INFO 707 --- [           main] n.d.d.service.SoundPlayerImpl            : meow

2018-07-17 22:46:53.931  INFO 707 --- [           main] .s.a.AnnotationAsyncExecutionInterceptor : No task executor bean found for async processing: no bean of type TaskExecutor and no bean named 'taskExecutor' either
Watching path: /home/pi/soundboard/sounds
2018-07-17 22:46:58.269  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/volume],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.setVolume(java.lang.Integer,java.lang.String)
2018-07-17 22:46:58.274  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/availableSounds],methods=[GET]}" onto public java.util.List<net.dirtydeeds.discordsoundboard.beans.SoundFile> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundFileList()
2018-07-17 22:46:58.276  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/soundCategories],methods=[GET]}" onto public java.util.Set<java.lang.String> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundCategories()
2018-07-17 22:46:58.278  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/playFile],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.playSoundFile(java.lang.String,java.lang.String)
2018-07-17 22:46:58.280  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/playUrl],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.playSoundUrl(java.lang.String,java.lang.String)
2018-07-17 22:46:58.282  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/sounds],methods=[GET]}" onto public java.util.List<net.dirtydeeds.discordsoundboard.beans.SoundFile> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundFileListNew()
2018-07-17 22:46:58.284  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/sounds],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.soundCommand(java.lang.String,java.lang.String)
2018-07-17 22:46:58.287  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/sounds/category],methods=[GET]}" onto public java.util.Set<java.lang.String> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundCategoriesNew()
2018-07-17 22:46:58.289  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/stop],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.stopPlayback(java.lang.String)
2018-07-17 22:46:58.291  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/volume],methods=[GET]}" onto public float net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getVolume()
2018-07-17 22:46:58.293  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/updateSoundList],methods=[GET]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.updateSoundList()
2018-07-17 22:46:58.295  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/playRandom],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.playRandomSoundFile(java.lang.String)
2018-07-17 22:46:58.297  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/users],methods=[GET]}" onto public java.util.List<net.dirtydeeds.discordsoundboard.beans.User> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getUsers()
2018-07-17 22:46:58.302  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/v2/api-docs],methods=[GET],produces=[application/json || application/hal+json]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)
2018-07-17 22:46:58.324  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configuration/security]}" onto org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.SecurityConfiguration> springfox.documentation.swagger.web.ApiResourceController.securityConfiguration()
2018-07-17 22:46:58.328  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configuration/ui]}" onto org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.UiConfiguration> springfox.documentation.swagger.web.ApiResourceController.uiConfiguration()
2018-07-17 22:46:58.332  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/swagger-resources]}" onto org.springframework.http.ResponseEntity<java.util.List<springfox.documentation.swagger.web.SwaggerResource>> springfox.documentation.swagger.web.ApiResourceController.swaggerResources()
2018-07-17 22:46:58.348  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2018-07-17 22:46:58.351  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2018-07-17 22:47:02.783  INFO 707 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@134b60d: startup date [Tue Jul 17 22:45:30 CEST 2018]; root of context hierarchy
2018-07-17 22:47:03.445  INFO 707 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-07-17 22:47:03.446  INFO 707 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-07-17 22:47:04.061  INFO 707 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2018-07-17 22:47:04.386  INFO 707 --- [           main] oConfiguration$WelcomePageHandlerMapping : Adding welcome page: class path resource [static/index.html]
2018-07-17 22:47:07.227  INFO 707 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2018-07-17 22:47:07.304  INFO 707 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2018-07-17 22:47:07.408  INFO 707 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2018-07-17 22:47:07.454  INFO 707 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2018-07-17 22:47:08.564  INFO 707 --- [inWS-ReadThread] n.d.jda.core.managers.AudioManager       : Audio System successfully setup!
2018-07-17 22:47:08.838  INFO 707 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2018-07-17 22:47:08.866  INFO 707 --- [           main] n.d.discordsoundboard.MainController     : Started MainController in 100.469 seconds (JVM running for 105.332)
2018-07-17 22:47:32.931  INFO 707 --- [inWS-ReadThread] n.d.d.listeners.ChatSoundBoardListener   : Attempting to play file: meow 1 times. Requested by Nacsis. ID: 374512228059316225
2018-07-17 22:47:33.185 ERROR 707 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item /home/pi/soundboard/sounds/meow.mp3

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:238) [classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:227) [classes!/:2.2.2-beta]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_171]
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87) ~[classes!/:2.2.2-beta]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]
Caused by: java.lang.UnsatisfiedLinkError: Required library at /natives/linux-arm/libconnector.so was not found
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:93) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:17) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3DecoderLibrary.getInstance(Mp3DecoderLibrary.java:14) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3Decoder.<init>(Mp3Decoder.java:22) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.<init>(Mp3TrackProvider.java:61) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:57) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:76) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:45) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:46) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:33) ~[classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:429) [classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:415) [classes!/:2.2.2-beta]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:219) [classes!/:2.2.2-beta]
	... 6 common frames omitted

2018-07-17 22:47:33.187 ERROR 707 --- [ader-2-thread-1] n.d.d.service.SoundPlayerImpl            : Something went wrong when looking up the track
``````

**Comment by Darkside138** [comment]
Looks like your rpi (Are you running Raspbian?) doesn't have the same
libraries available as Ubuntu. In this case it's looking for libconnector.so
and could not find it.

**Comment by Nacsis** [comment]
Hi,
thanks for hint. Yes, I'm running Raspbian(lite).
I tried downloading the arm libconnector.so from somewhere else, opened the jar with my archive manager and placed the library in BOOT-INF/classes/natives/linux-arm/ as suggested here:
https://github.com/sedmelluq/lavaplayer/issues/41
It worked out for me.
You might consider adding the library to the project, since running the Bot on a RPi with Raspbian is a common case.
Greetings,
Nacsis
