### ISSUE TITLE
The bot isn't working anymore (disconnecting, and reconnecting) :'(

### ISSUE THREAD

**Issue by ALink95** [Darkside138/DiscordSoundboard#117]
Hello,
When i launch the bot it keeps disconnecting and reconnecting without playing any sounds, and it was working a few days ago!
I'm not really up with java so i can't really understand what's going on but if you ask me i can give you more details about the problem

**Comment by tyler7216** [comment]
We are also experiencing the same issue with the bot in our server as of a few days ago. 

We are using DiscordSoundboard-1.4.11 and getting the following error when attempting to play sounds:
[17:54:44] [Fatal] [JDAAudioSocket]: Encountered an exception:
[17:54:44] [Fatal] [JDAAudioSocket]: java.net.SocketTimeoutException: Receive timed out
        at java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
        at java.net.DualStackPlainDatagramSocketImpl.receive0(Unknown Source)
        at java.net.AbstractPlainDatagramSocketImpl.receive(Unknown Source)
        at java.net.DatagramSocket.receive(Unknown Source)
        at net.dv8tion.jda.audio.AudioWebSocket.handleUdpDiscovery(AudioWebSocket.java:373)
        at net.dv8tion.jda.audio.AudioWebSocket.onTextMessage(AudioWebSocket.java:154)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

Afterwards the bot disconnects from the channel. I downloaded the latest version (2.2.2) and am now getting the same issue as OP, where the bot will fail to play the sound and will get stuck in a loop of connecting and disconnecting from the channel.  

The error I get from v2.2.2 is:
java.lang.IllegalStateException: Invalid audio format 3, must be 1 (PCM)
        at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader$InfoBuilder.validateFormat(WavFileLoader.java:103) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader$InfoBuilder.build(WavFileLoader.java:95) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader$InfoBuilder.access$300(WavFileLoader.java:85) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.wav.WavFileLoader.parseHeaders(WavFileLoader.java:50) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.wav.WavContainerProbe.probe(WavContainerProbe.java:45) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:76) [classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61) [classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:45) [classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:46) [classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:33) [classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:429) [classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:415) [classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:219) [classes!/:2.2.2-beta]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_231]
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87) ~[classes!/:2.2.2-beta]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_231]

2019-10-21 17:58:28.722 ERROR 680 --- [ader-2-thread-1] n.d.d.service.SoundPlayerImpl            : Unknown file format.

Thanks in advance for your help!

**Comment by sskrobe** [comment]
We already have a thread open, but have been very unsuccessful. 


https://github.com/Darkside138/DiscordSoundboard/issues/112

**Comment by Darkside138** [comment]
See updates in the #112 thread

**Comment by Darkside138** [comment]
Closing this as a dup.
