### ISSUE TITLE
application.properties not found

### ISSUE THREAD

**Issue by Trytotry2** [Darkside138/DiscordSoundboard#120]
Hi,
I have been using your bot since lot of months on my Discord and everything was going well since my version wasn't support anymore.

So I decided to upgrade on the last version. I tried the config on Windows, everything works well, so I import it on my raspberry pi to let it run all the time and nothing is working...

When I launch it, the terminal tell me :
```
[WARN] SoundPlayerImpl - Could not find application.properties files.
[WARN] SoundPlayerImpl - Loading application.properties file from ressources folder
[FATAL] SoundPlayerImpl - You do not have an application.properties file. Please create one.
[WARN] SoundPlayerImpl - The config was not populated. Please enter an email and password.
[INFO] SoundPlayerImpl - Loading from /home/pi/Desktop/DiscordSoundboard/lib/sounds
```

Any idea of what I could did wrong ?

Thank's for your help.

**Comment by Trytotry2** [comment]
Well, i'm not a pro-coder so I guess you did big change since the last version I used. OIn Windows everything works well but I'm launching the bot with DiscordSoundboard.bat in the bin folder. On my pi, I launch the bot in the lib folder by using :

```
#!/bin/sh
java -jar DiscordSoundboard-3.0.3.jar
```

Maybe i'm wrong, but how to launch it if it's not like that ? (This commande was perfectly working with the last version).

**Comment by Trytotry2** [comment]
Trie to copy the application.properties file in the bin folder and the WARN and FATAL lines have disappeared but the bot wasn't able to use the sounds folder in the lib folder.
`net.dirtydeeds.discordsoundboard.SoundPlaybackException: Could not find sound file that was requested.
`

I had to copy them to into the bin sounds folder and now it works but I have a 

Now, the sound are find but I have ERROR 1300

`[INFO] ChatListener - Attempting to play file: goldeneye 1 times. Requested by Anarhim.
2019-11-08 21:40:32.809  INFO 1300 --- [ader-2-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library libmpg123-0: loading with filter com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader$$Lambda$919/27503157@a12da5
2019-11-08 21:40:32.819  INFO 1300 --- [ader-2-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library connector: loading with filter null
2019-11-08 21:40:32.850 ERROR 1300 --- [ader-2-thread-1] c.s.l.c.natives.NativeLibraryLoader      : Native library {}: loading failed.

java.lang.UnsatisfiedLinkError: Required library was not found
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:128) [lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:113) [lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadAndRemember(NativeLibraryLoader.java:85) [lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:70) [lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3DecoderLibrary.getInstance(Mp3DecoderLibrary.java:14) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3Decoder.<init>(Mp3Decoder.java:25) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.<init>(Mp3TrackProvider.java:66) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:54) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:91) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:76) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:58) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:62) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:45) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) [lavaplayer-1.3.23.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]

2019-11-08 21:40:32.860 ERROR 1300 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item /home/pi/Desktop/DiscordSoundboard/lib/sounds/goldeneye.mp3

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:237) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:226) [lavaplayer-1.3.23.jar!/:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_221]
Caused by: java.lang.UnsatisfiedLinkError: com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3DecoderLibrary.create()J
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3DecoderLibrary.create(Native Method) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3Decoder.<init>(Mp3Decoder.java:26) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.<init>(Mp3TrackProvider.java:66) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:54) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:91) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:76) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:58) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:62) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:45) ~[lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:437) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:419) [lavaplayer-1.3.23.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:218) [lavaplayer-1.3.23.jar!/:na]
	... 4 common frames omitted
`

I think the message is clear. It's telling me that I'm not a hacker and I should ask you for help instead of modifying something that I do not understand...

**Comment by Darkside138** [comment]
The issue is that the libraries that do playing aren't compiled for arm
processors. Therefore it can't load them. Basically, the bot no longer
works on the pi. I think it's possible to compile the libraries but I'm not
exactly sure how.

**Comment by Trytotry2** [comment]
Oh fuck, that's really sad. Is there a lower version that still works on pi ? (I have been using your bot since almost the beginning of the project so everyone in the team know how to use it and enjoy it so I would like to keep it instead of trying another or just shut it down...)

**Comment by Darkside138** [comment]
I could try to compile the libraries for pi. I'll look into that when I get
a chance. All the older versions do not work because the discord API
changed so the older versions are broken.

**Comment by Darkside138** [comment]
I found this. Could be helpful.

https://github.com/sedmelluq/lavaplayer/issues/16

**Comment by Darkside138** [comment]
OK, that link is pretty old. That lib isn't going to work. I'm trying to include the correct library in the release. Let me see what I can do. For now this is the lib you need you should be able to manually add it if you want: https://bintray.com/sedmelluq/com.sedmelluq/lavaplayer-natives-extra/1.3.13#files/com%2Fsedmelluq%2Flavaplayer-natives-extra%2F1.3.13
