### ISSUE TITLE
Raspbian host. Bot won't play sound, discord settings correct. Log attached.

### ISSUE THREAD

**Issue by daniel-san-fried** [Darkside138/DiscordSoundboard#142]
Hello Darkside138 and community. I got this issue on my RaspberryPi 4 where my soundboard won't play sounds inside a channel.

What he does:
- He is set up and works in theory
- He can connect to a channel
- He listens to all commands (including "?sound")
- He is repeating to all commands

What he does not:
- Play a local sound (*.mp3 for example).
The circle is not lit, so the problem is not the sound output or the file, it is the PI
- Play a youtube link

My Terminal shows me what is going on but I am not experienced that much with the PI and Raspbian so I hope I could find help.
I pay you a beer for sure if you can help me, we love the bot on our server but I want to host it 24/7.

Thank you very much.
Daniel 

___ LOG ___

[INFO] ChatListener - Attempting to play file: afrika 1 times. Requested by Kidneybabyonemortime.
2020-06-23 20:04:33.443  WARN 14776 --- [ader-2-thread-1] c.s.d.l.c.MediaContainerDetection        : Attempting to detect file with container mp3 failed.

java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Required library was not found
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadAndRemember(NativeLibraryLoader.java:90) ~[lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.load(NativeLibraryLoader.java:70) ~[lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:21) ~[lavaplayer-1.3.23.jar!/:na]
	at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.init(SoundPlayerImpl.java:89) ~[classes!/:3.0.4]
	at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.<init>(SoundPlayerImpl.java:69) ~[classes!/:3.0.4]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_212]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_212]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:200) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:308) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:293) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) ~[spring-beans-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.2.0.RELEASE.jar!/:5.2.0.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.0.RELEASE.jar!/:2.2.0.RELEASE]
	at net.dirtydeeds.discordsoundboard.MainController.main(MainController.java:20) ~[classes!/:3.0.4]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[DiscordSoundboard-3.0.4.jar:3.0.4]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[DiscordSoundboard-3.0.4.jar:3.0.4]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[DiscordSoundboard-3.0.4.jar:3.0.4]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[DiscordSoundboard-3.0.4.jar:3.0.4]
Caused by: java.lang.UnsatisfiedLinkError: Required library was not found
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.extractLibraryFromResources(NativeLibraryLoader.java:128) ~[lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadInternal(NativeLibraryLoader.java:113) ~[lava-common-1.1.0.jar!/:na]
	at com.sedmelluq.lava.common.natives.NativeLibraryLoader.loadAndRemember(NativeLibraryLoader.java:85) ~[lava-common-1.1.0.jar!/:na]
	... 38 common frames omitted

**Comment by cnschu** [comment]
is the bug still relevant?

**Comment by cnschu** [comment]
it seems you are missing "lava-common".
