### ISSUE TITLE
List 1 still bugged

### ISSUE THREAD

**Issue by daniel-san-fried** [Darkside138/DiscordSoundboard#167]
The command !list 1 (when having more than fits on one page) is broken. Is there a maximum sound file cap or why does this happen? I have the errorlog attatched. Thanks!

2021-07-17 13:06:55.431 ERROR 16312 --- [inWS-ReadThread] net.dv8tion.jda.api.JDA                  : One of the EventListeners had an uncaught exception

java.lang.IllegalArgumentException: Provided text for message must be less than 2000 characters in length
        at net.dv8tion.jda.internal.utils.Checks.check(Checks.java:43) ~[JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.api.entities.MessageChannel.sendMessage(MessageChannel.java:343) ~[JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.entities.PrivateChannelImpl.sendMessage(PrivateChannelImpl.java:141) ~[JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.replyByPrivateMessage(ChatSoundBoardListener.java:504) ~[classes!/:3.0.6]
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.listCommand(ChatSoundBoardListener.java:443) ~[classes!/:3.0.6]
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:83) ~[classes!/:3.0.6]
        at net.dv8tion.jda.api.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:431) ~[JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.api.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:96) ~[JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handleInternally(EventManagerProxy.java:82) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.hooks.EventManagerProxy.handle(EventManagerProxy.java:69) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.JDAImpl.handleEvent(JDAImpl.java:147) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:122) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.handle.SocketHandler.handle(SocketHandler.java:36) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onDispatch(WebSocketClient.java:948) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onEvent(WebSocketClient.java:835) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.requests.WebSocketClient.handleEvent(WebSocketClient.java:813) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at net.dv8tion.jda.internal.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:986) [JDA-4.2.0_214.jar!/:4.2.0_214]
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:385) [nv-websocket-client-2.10.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:276) [nv-websocket-client-2.10.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:996) [nv-websocket-client-2.10.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:755) [nv-websocket-client-2.10.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108) [nv-websocket-client-2.10.jar!/:na]
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64) [nv-websocket-client-2.10.jar!/:na]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) [nv-websocket-client-2.10.jar!/:na]

**Comment by Darkside138** [comment]
Yeah, it's supposed to split the message into strings of less than 2000 but there must be a bug.

**Comment by Darkside138** [comment]
Try setting this in your application.properties if it's not there:
`message_size_limit=2000`

If that doesn't work you could set that number lower like 1500

**Comment by daniel-san-fried** [comment]
> If that doesn't work you could set that number lower like 1500

This did the trick by the way! Thank you very much for replying!
