### ISSUE TITLE
Unknown error, possibly java related?

### ISSUE THREAD

**Issue by BoksmanTheMighty** [Darkside138/DiscordSoundboard#172]
I really haven't the slightest clue what's going on here. I've run the .bat through CMD and recieved this error. Please help!

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/dirtydeeds/discordsoundboard/MainController has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:46)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Comment by schallakuchen** [comment]
The Java version installed on your computer is too old.
Quote from the readme.md "Must have Java 17+ 64bit version installed in order for the soundboard to work properly"

**Comment by BoksmanTheMighty** [comment]
shit, i got the notification from your response ages ago and just forgot to comment. In the time between, I've completely reset my computer. Probably for the best that you closed the topic.
