### ISSUE TITLE
Commands Won't Disappear + List Not Working

### ISSUE THREAD

**Issue by JoshCarlyle** [Darkside138/DiscordSoundboard#29]
**Here's the log for when inputting a soundboard command :** 

````
C:\Users\joshu\Desktop\Discord Bots\SoundboardBOt>java -jar DiscordSoundboard.jar net.dirtydeeds.discordsoundboard.MainController
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/joshu/Desktop/Discord%20Bots/SoundboardBOt/DiscordSoundboard.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/joshu/Desktop/Discord%20Bots/SoundboardBOt/DiscordSoundboard.jar!/lib/logback-classic-1.1.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v1.4.8)

2016-12-23 14:45:02.146  INFO 3872 --- [           main] n.d.discordsoundboard.MainController     : Starting MainController v1.4.8 on DESKTOP-VFB0GFN with PID 3872 (C:\Users\joshu\Desktop\Discord Bots\SoundboardBOt\DiscordSoundboard.jar started by joshu in C:\Users\joshu\Desktop\Discord Bots\SoundboardBOt)
2016-12-23 14:45:02.151  INFO 3872 --- [           main] n.d.discordsoundboard.MainController     : No active profile set, falling back to default profiles: default
2016-12-23 14:45:02.190  INFO 3872 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1e8829: startup date [Fri Dec 23 14:45:02 AEST 2016]; root of context hierarchy
2016-12-23 14:45:03.410  INFO 3872 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2016-12-23 14:45:03.640  INFO 3872 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2016-12-23 14:45:03.695  INFO 3872 --- [           main] o.s.s.a.AsyncAnnotationBeanPostProcessor : No TaskExecutor bean found for async annotation processing.
2016-12-23 14:45:03.783  INFO 3872 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$f3b77930] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2016-12-23 14:45:04.307  INFO 3872 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2016-12-23 14:45:04.322  INFO 3872 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2016-12-23 14:45:04.323  INFO 3872 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.32
2016-12-23 14:45:04.473  INFO 3872 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2016-12-23 14:45:04.473  INFO 3872 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2284 ms
2016-12-23 14:45:04.886  INFO 3872 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2016-12-23 14:45:04.892  INFO 3872 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2016-12-23 14:45:04.893  INFO 3872 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2016-12-23 14:45:04.893  INFO 3872 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2016-12-23 14:45:04.894  INFO 3872 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2016-12-23 14:45:05.226  INFO 3872 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2016-12-23 14:45:05.236  INFO 3872 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2016-12-23 14:45:05.318  INFO 3872 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {4.3.11.Final}
2016-12-23 14:45:05.322  INFO 3872 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2016-12-23 14:45:05.323  INFO 3872 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
2016-12-23 14:45:08.705  INFO 3872 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
2016-12-23 14:45:08.797  INFO 3872 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2016-12-23 14:45:08.914  INFO 3872 --- [           main] o.h.h.i.ast.ASTQueryTranslatorFactory    : HHH000397: Using ASTQueryTranslatorFactory
2016-12-23 14:45:09.152  INFO 3872 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000227: Running hbm2ddl schema export
2016-12-23 14:45:09.163  INFO 3872 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000230: Schema export complete
[14:45:09] [Info] [JDAAudioManager]: Audio System successfully setup!
[14:45:09] [Warning] [JDA]: BulkDeleteSplitting is enabled. For best performance, please look at the javadoc for JDABuilder#setBulkDeleteEnabled(boolean).
[14:45:09] [Info] [JDA]: JDA starting...
[14:45:10] [Info] [JDA]: Login Successful!
[14:45:11] [Info] [JDASocket]: Connected to WebSocket
[14:45:11] [Info] [JDA]: Finished Loading!
[14:45:11] [Fatal] [JDA]: Encountered an exception:
[14:45:11] [Fatal] [JDA]: javax.imageio.IIOException: Can't read input file!
        at javax.imageio.ImageIO.read(Unknown Source)
        at net.dv8tion.jda.utils.AvatarUtil.getAvatar(AvatarUtil.java:41)
        at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.initializeDiscordBot(SoundPlayerImpl.java:656)
        at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.init(SoundPlayerImpl.java:79)
        at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.<init>(SoundPlayerImpl.java:74)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:267)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1143)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1046)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
        at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1191)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1180)
        at net.dirtydeeds.discordsoundboard.MainController.main(MainController.java:20)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:54)
        at java.lang.Thread.run(Unknown Source)

[14:45:12] [Info] [SoundPlayerImpl]: Loading from C:\Users\joshu\Desktop\Discord Bots\SoundboardBOt/sounds
Watching path: C:\Users\joshu\Desktop\Discord Bots\SoundboardBOt\sounds
[14:45:12] [Info] [SoundPlayerImpl]: 30e5
[14:45:12] [Info] [SoundPlayerImpl]: 411
[14:45:12] [Info] [SoundPlayerImpl]: abdul
[14:45:12] [Info] [SoundPlayerImpl]: bangarang
[14:45:12] [Info] [SoundPlayerImpl]: bitch
[14:45:12] [Info] [SoundPlayerImpl]: boysinblue
[14:45:12] [Info] [SoundPlayerImpl]: crazy
[14:45:12] [Info] [SoundPlayerImpl]: democracy
[14:45:12] [Info] [SoundPlayerImpl]: druggo
[14:45:12] [Info] [SoundPlayerImpl]: fart1
[14:45:12] [Info] [SoundPlayerImpl]: fart2
[14:45:12] [Info] [SoundPlayerImpl]: fart3
[14:45:12] [Info] [SoundPlayerImpl]: fiddybucks
[14:45:12] [Info] [SoundPlayerImpl]: gtasa
[14:45:12] [Info] [SoundPlayerImpl]: gun
[14:45:12] [Info] [SoundPlayerImpl]: headlock
[14:45:12] [Info] [SoundPlayerImpl]: hellyeah
[14:45:12] [Info] [SoundPlayerImpl]: howdoidrive
[14:45:12] [Info] [SoundPlayerImpl]: initiald1
[14:45:12] [Info] [SoundPlayerImpl]: initiald2
[14:45:12] [Info] [SoundPlayerImpl]: judo
[14:45:12] [Info] [SoundPlayerImpl]: ks
[14:45:12] [Info] [SoundPlayerImpl]: limp
[14:45:12] [Info] [SoundPlayerImpl]: meal
[14:45:12] [Info] [SoundPlayerImpl]: monkey
[14:45:12] [Info] [SoundPlayerImpl]: mtndew
[14:45:12] [Info] [SoundPlayerImpl]: outburst
[14:45:12] [Info] [SoundPlayerImpl]: penis
[14:45:12] [Info] [SoundPlayerImpl]: perfect
[14:45:12] [Info] [SoundPlayerImpl]: skitz
[14:45:12] [Info] [SoundPlayerImpl]: tree
[14:45:12] [Info] [SoundPlayerImpl]: trowel
[14:45:12] [Info] [SoundPlayerImpl]: uracunt
[14:45:12] [Info] [SoundPlayerImpl]: wadiyatalkinabeet
[14:45:12] [Info] [SoundPlayerImpl]: wooh
[14:45:12] [Info] [SoundPlayerImpl]: wooh2
[14:45:12] [Info] [SoundPlayerImpl]: yes
[14:45:12] [Info] [SoundPlayerImpl]: yes2
2016-12-23 14:45:12.956  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/volume],methods=[GET]}" onto public float net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getVolume()
2016-12-23 14:45:12.958  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/playFile],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.playSoundFile(java.lang.String,java.lang.String)
2016-12-23 14:45:12.958  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/availableSounds],methods=[GET]}" onto public java.util.List<net.dirtydeeds.discordsoundboard.beans.SoundFile> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundFileList()
2016-12-23 14:45:12.959  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/volume],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.setVolume(java.lang.Integer)
2016-12-23 14:45:12.959  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/playUrl],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.playSoundUrl(java.lang.String,java.lang.String)
2016-12-23 14:45:12.960  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/stop],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.stopPlayback()
2016-12-23 14:45:12.960  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/sounds],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.soundCommand(java.lang.String,java.lang.String)
2016-12-23 14:45:12.961  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/playRandom],methods=[POST]}" onto public org.springframework.http.HttpStatus net.dirtydeeds.discordsoundboard.web.SoundboardRestController.playRandomSoundFile(java.lang.String)
2016-12-23 14:45:12.962  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/sounds],methods=[GET]}" onto public java.util.List<net.dirtydeeds.discordsoundboard.beans.SoundFile> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundFileListNew()
2016-12-23 14:45:12.962  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/sounds/category],methods=[GET]}" onto public java.util.Set<java.lang.String> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundCategoriesNew()
2016-12-23 14:45:12.963  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/soundCategories],methods=[GET]}" onto public java.util.Set<java.lang.String> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getSoundCategories()
2016-12-23 14:45:12.963  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/soundsApi/users],methods=[GET]}" onto public java.util.List<net.dirtydeeds.discordsoundboard.beans.User> net.dirtydeeds.discordsoundboard.web.SoundboardRestController.getUsers()
2016-12-23 14:45:12.964  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/v2/api-docs],methods=[GET],produces=[application/json || application/hal+json]}" onto public org.springframework.http.ResponseEntity<springfox.documentation.spring.web.json.Json> springfox.documentation.swagger2.web.Swagger2Controller.getDocumentation(java.lang.String,javax.servlet.http.HttpServletRequest)
2016-12-23 14:45:12.967  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/swagger-resources]}" onto org.springframework.http.ResponseEntity<java.util.List<springfox.documentation.swagger.web.SwaggerResource>> springfox.documentation.swagger.web.ApiResourceController.swaggerResources()
2016-12-23 14:45:12.969  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configuration/ui]}" onto org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.UiConfiguration> springfox.documentation.swagger.web.ApiResourceController.uiConfiguration()
2016-12-23 14:45:12.970  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/configuration/security]}" onto org.springframework.http.ResponseEntity<springfox.documentation.swagger.web.SecurityConfiguration> springfox.documentation.swagger.web.ApiResourceController.securityConfiguration()
2016-12-23 14:45:12.972  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error]}" onto public org.springframework.http.ResponseEntity<java.util.Map<java.lang.String, java.lang.Object>> org.springframework.boot.autoconfigure.web.BasicErrorController.error(javax.servlet.http.HttpServletRequest)
2016-12-23 14:45:12.973  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerMapping : Mapped "{[/error],produces=[text/html]}" onto public org.springframework.web.servlet.ModelAndView org.springframework.boot.autoconfigure.web.BasicErrorController.errorHtml(javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse)
2016-12-23 14:45:13.287  INFO 3872 --- [           main] s.w.s.m.m.a.RequestMappingHandlerAdapter : Looking for @ControllerAdvice: org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@1e8829: startup date [Fri Dec 23 14:45:02 AEST 2016]; root of context hierarchy
2016-12-23 14:45:13.480  INFO 3872 --- [           main] o.s.w.s.c.a.WebMvcConfigurerAdapter      : Adding welcome page: class path resource [static/index.html]
2016-12-23 14:45:13.506  INFO 3872 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Root mapping to handler of type [class org.springframework.web.servlet.mvc.ParameterizableViewController]
2016-12-23 14:45:13.530  INFO 3872 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/webjars/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-12-23 14:45:13.530  INFO 3872 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-12-23 14:45:13.609  INFO 3872 --- [           main] o.s.w.s.handler.SimpleUrlHandlerMapping  : Mapped URL path [/**/favicon.ico] onto handler of type [class org.springframework.web.servlet.resource.ResourceHttpRequestHandler]
2016-12-23 14:45:13.893  INFO 3872 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2016-12-23 14:45:13.901  INFO 3872 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2016-12-23 14:45:13.919  INFO 3872 --- [           main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2016-12-23 14:45:13.926  INFO 3872 --- [           main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2016-12-23 14:45:14.123  INFO 3872 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat started on port(s): 8080 (http)
2016-12-23 14:45:14.128  INFO 3872 --- [           main] n.d.discordsoundboard.MainController     : Started MainController in 12.274 seconds (JVM running for 12.87)
[14:45:40] [Info] [ChatListener]: Attempting to play file: yes. Requested by Josh.
````
**The command fails to disappear.**

**Here's a log after that where I've asked the bot for the list:**
`[14:47:00] [Info] [ChatListener]: Responding to list command. Requested by Josh.
[14:47:00] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[14:47:00] [Fatal] [JDA]: Encountered an exception:
[14:47:00] [Fatal] [JDA]: net.dv8tion.jda.exceptions.BlockedException: The requested User blocks you or disallows you otherwise from PMing him!
        at net.dv8tion.jda.entities.impl.PrivateChannelImpl.sendMessage(PrivateChannelImpl.java:102)
        at net.dv8tion.jda.entities.impl.PrivateChannelImpl.sendMessage(PrivateChannelImpl.java:80)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.replyByPrivateMessage(ChatSoundBoardListener.java:327)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:80)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:184)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleDefaultMessage(MessageReceivedHandler.java:94)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:50)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:596)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)
`
**I have not blocked the bot, this just happened spontaneously one day and has been happening ever since to me and others in my discord (and also it seems others on github too).**

**Comment by ObscenityIB** [comment]
yeah, updating to the latest release didnt help either

**Comment by z1g** [comment]
Issues #26 and #27 already address this and it would be easier for the dev to follow if comments were posted in existing issues rather than submitting new issues. 

You do have some interesting sound names there though heh.

**Comment by Darkside138** [comment]
I found the issue. Discord changed the way the auth token is returned after updating the avatar. Updating the avatar is attempted at the start of the bot. When that fails the token gets corrupted and none of the commands work after that. I have it fixed and will get a new release uploaded ASAP.
