### ISSUE TITLE
The requested User blocks you

### ISSUE THREAD

**Issue by FishMissile** [Darkside138/DiscordSoundboard#30]
Apparently the bot has blocked me? The bot works fine for everyone else but will not respond to me. I have not blocked it...

```
[12:09:02] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[12:09:02] [Fatal] [JDA]: Encountered an exception:
[12:09:02] [Fatal] [JDA]: net.dv8tion.jda.exceptions.BlockedException: The requested User blocks you or disallows you otherwise from PMing him!
        at net.dv8tion.jda.entities.impl.PrivateChannelImpl.sendMessage(PrivateChannelImpl.java:102)
        at net.dv8tion.jda.entities.impl.PrivateChannelImpl.sendMessage(PrivateChannelImpl.java:80)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.replyByPrivateMessage(ChatSoundBoardListener.java:327)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:97)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:184)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleDefaultMessage(MessageReceivedHandler.java:94)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:50)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:596)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)
```

**Comment by z1g** [comment]
Would probably be best if folks would not post duplicate issues for issues that are already open.

**Comment by FishMissile** [comment]
Yes, I should have seen that. Issue closed.
