### ISSUE TITLE
I don't take orders from you.

### ISSUE THREAD

**Issue by z1g** [Darkside138/DiscordSoundboard#31]
First off, thank you so much for working on this.  Please do not spend your holiday working on this.

I have updated to 1.49 and all commands result in a DM from the bot that say "I don't take orders from you."

No errors in the console.

**Comment by Darkside138** [comment]
Sounds like something is wrong with the blocked users functionality. I'll
take a look when I can. Merry Christmas!

**Comment by Darkside138** [comment]
I'm thinking that you could probably fix the error by removing the line that defines allowed users in your app.properties file. It would be a temp fix while I fix the code.

**Comment by madMonKAY** [comment]
Hey Darkside it seems like this error is also causing the remove function and the add function to stop working.
When users try to add via filetransfer it seems like nothing happens.
Adding log from remove command.
`[04:39:52] [Fatal] [JDA]: One of the EventListeners had an uncaught exception
[04:39:52] [Fatal] [JDA]: Encountered an exception:
[04:39:52] [Fatal] [JDA]: java.lang.NullPointerException
        at net.dv8tion.jda.utils.PermissionUtil.checkPermission(PermissionUtil.java:274)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:183)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:184)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleDefaultMessage(MessageReceivedHandler.java:94)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:50)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:596)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)`

**Comment by z1g** [comment]
Thanks Darkside, commenting that out works like a champ.

**Comment by Darkside138** [comment]
Fixed with 1.4.10

**Comment by Darkside138** [comment]
@madMonKAY I'm thinking your issue should be fixed as well. Please open a new issue if it's not.
