### ISSUE TITLE
2.0.1 will only play stereo files

### ISSUE THREAD

**Issue by crowbarto** [Darkside138/DiscordSoundboard#52]
This is attempting to play a 44100Hz Mono mp3 file:
No issue if i duplicate the channel to convert the mp3 to stereo
Here is pastebin of the .log http://pastebin.com/EqXvkAQ3

 2017-02-14 22:46:42.001  WARN 6060 --- [ader-2-thread-1] c.s.d.l.c.MediaContainerDetection        : Attempting to detect file with container MP3 failed.

java.lang.IllegalStateException: Mp3 frame not found.
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.runFrameScanLoop(Mp3FrameReader.java:77) ~[DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3FrameReader.scanForFrame(Mp3FrameReader.java:53) ~[DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.parseHeaders(Mp3TrackProvider.java:71) ~[DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:52) ~[DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:56) [DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:41) [DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:48) [DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:35) [DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:396) [DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:382) [DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:199) [DiscordSoundboard.jar!/:2.0.1-beta]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[na:1.8.0_121]
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.executeQueue(OrderedExecutor.java:98) ~[DiscordSoundboard.jar!/:2.0.1-beta]
        at com.sedmelluq.discord.lavaplayer.tools.OrderedExecutor$ChannelRunnable.run(OrderedExecutor.java:87) ~[DiscordSoundboard.jar!/:2.0.1-beta]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:1.8.0_121]
        at java.lang.Thread.run(Unknown Source) ~[na:1.8.0_121]

2017-02-14 22:46:42.002 ERROR 6060 --- [ader-2-thread-1] n.d.d.service.SoundPlayerImpl            : Unknown file format.

**Comment by crowbarto** [comment]
Ok I changed build.gradle dependencies for jda 3 and lavaplayer to:

    compile 'net.dv8tion:JDA:3.0.BETA2_147'
    compile 'com.sedmelluq:lavaplayer:1.2.29'

and rebuilt

Soundbot will now play most non stereo files for me now.  I just re sample the few odd wav files that I have probs with using Audacity to mp3 and all is good.  Bot is now running like a champ.  24+ hours with no errors or hickups!

Keep up the great work on this bot!

**Comment by Darkside138** [comment]
That's great. You could put in a MR with those build changes if you want
and I could accept them into the beta branch.

**Comment by xombiemike** [comment]
Yep, mono wav files sound crazy bad. I have a batch converter if anyone needs it that will turn wav files into stereo MP3s. Email xombiemike@gmail.com for it.
