### ISSUE TITLE
Gives an error on boot

### ISSUE THREAD

**Issue by killerfurze** [Darkside138/DiscordSoundboard#74]
So while the bot is loading I get this error

```[16:24:20] [Fatal] [JDASocket]: Encountered an exception:
[16:24:20] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 356288434702123009
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildChannelPass(EntityBuilder.java:405)
        at net.dv8tion.jda.core.entities.EntityBuilder.createGuildFirstPass(EntityBuilder.java:293)
        at net.dv8tion.jda.core.handle.GuildCreateHandler.handleInternally(GuildCreateHandler.java:39)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:688)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:437)
        at net.dv8tion.jda.core.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:721)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:272)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:992)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:751)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:110)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:66)
```
Here's some info that might help:
OS: Windows 10
Java: Latest (not sure of the exact number)
Discord Build: Canary
Bot Version: 2.0.1-BETA
Server chats: Catagorized
Bot perms: all perms

**Comment by killerfurze** [comment]
Here is the full log from boot to error
https://pastebin.com/Vennp1zn

**Comment by AnderAreizaga** [comment]
Just i know why this happens but i don't know how to solve it. This is because the new category system added to discord. Still don't know how to solve it

**Comment by AnderAreizaga** [comment]
i have the same error too

**Comment by Darkside138** [comment]
Yeah the new categories broke the bot. Not sure if/when I'll get around to
fixing this. I just don't really have the time right now.

**Comment by Darkside138** [comment]
The new release is out. 2.1.1-BETA. This will fix the category problem.
