### ISSUE TITLE
Bot not working after the Channel Categories update

### ISSUE THREAD

**Issue by GuidoFida** [Darkside138/DiscordSoundboard#76]
Edit: Current work around is to stop the bot, delete the categories, start the bot and join a voice channel, then make the categories again. But you have to do this anytime the bot turns off which isn't ideal.

This is the log, towards the bottom you can see it referencing the names of my categories:

M:\Discord Bot\Soundboard>java -jar DiscordSoundboard.jar net.dirtydeeds.discordsoundboard.MainController
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/M:/Discord%20Bot/Soundboard/DiscordSoundboard.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/M:/Discord%20Bot/Soundboard/DiscordSoundboard.jar!/lib/logback-classic-1.1.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::               (v1.4.12)

2017-09-23 02:13:42.246  INFO 14852 --- [           main] n.d.discordsoundboard.MainController     : Starting MainController v1.4.12 on Linos-PC with PID 14852 (M:\Discord Bot\Soundboard\DiscordSoundboard.jar started by Linos in M:\Discord Bot\Soundboard)
2017-09-23 02:13:42.250  INFO 14852 --- [           main] n.d.discordsoundboard.MainController     : No active profile set, falling back to default profiles: default
2017-09-23 02:13:42.361  INFO 14852 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@673fbde3: startup date [Sat Sep 23 02:13:42 EDT 2017]; root of context hierarchy
2017-09-23 02:13:46.873  INFO 14852 --- [           main] o.s.b.f.s.DefaultListableBeanFactory     : Overriding bean definition for bean 'beanNameViewResolver' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/ErrorMvcAutoConfiguration$WhitelabelErrorViewConfiguration.class]] with [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.boot.autoconfigure.web.WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter; factoryMethodName=beanNameViewResolver; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/boot/autoconfigure/web/WebMvcAutoConfiguration$WebMvcAutoConfigurationAdapter.class]]
2017-09-23 02:13:48.077  INFO 14852 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2017-09-23 02:13:48.444  INFO 14852 --- [           main] o.s.s.a.AsyncAnnotationBeanPostProcessor : No TaskExecutor bean found for async annotation processing.
2017-09-23 02:13:48.607  INFO 14852 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [class org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$755ee1cb] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2017-09-23 02:13:50.426  INFO 14852 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-09-23 02:13:50.482  INFO 14852 --- [           main] o.apache.catalina.core.StandardService   : Starting service Tomcat
2017-09-23 02:13:50.492  INFO 14852 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.0.32
2017-09-23 02:13:50.827  INFO 14852 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-09-23 02:13:50.828  INFO 14852 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 8471 ms
2017-09-23 02:13:52.020  INFO 14852 --- [ost-startStop-1] o.s.b.c.e.ServletRegistrationBean        : Mapping servlet: 'dispatcherServlet' to [/]
2017-09-23 02:13:52.036  INFO 14852 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-09-23 02:13:52.038  INFO 14852 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-09-23 02:13:52.047  INFO 14852 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-09-23 02:13:52.052  INFO 14852 --- [ost-startStop-1] o.s.b.c.embedded.FilterRegistrationBean  : Mapping filter: 'requestContextFilter' to: [/*]
2017-09-23 02:13:53.208  INFO 14852 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2017-09-23 02:13:53.272  INFO 14852 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
        name: default
        ...]
2017-09-23 02:13:53.429  INFO 14852 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {4.3.11.Final}
2017-09-23 02:13:53.447  INFO 14852 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2017-09-23 02:13:53.454  INFO 14852 --- [           main] org.hibernate.cfg.Environment            : HHH000021: Bytecode provider name : javassist
2017-09-23 02:13:57.790  INFO 14852 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {4.0.5.Final}
2017-09-23 02:13:57.969  INFO 14852 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
2017-09-23 02:13:58.482  INFO 14852 --- [           main] o.h.h.i.ast.ASTQueryTranslatorFactory    : HHH000397: Using ASTQueryTranslatorFactory
2017-09-23 02:13:58.754  INFO 14852 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000227: Running hbm2ddl schema export
2017-09-23 02:13:58.768  INFO 14852 --- [           main] org.hibernate.tool.hbm2ddl.SchemaExport  : HHH000230: Schema export complete
[02:14:00] [Info] [JDAAudioManager]: Audio System successfully setup!
[02:14:00] [Warning] [JDA]: BulkDeleteSplitting is enabled. For best performance, please look at the javadoc for JDABuilder#setBulkDeleteEnabled(boolean).
[02:14:00] [Info] [JDA]: JDA starting...
[02:14:01] [Info] [JDA]: Login Successful!
[02:14:02] [Info] [JDASocket]: Connected to WebSocket
[02:14:02] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"test","position":0,"id":"360598930553176065","type":4}
[02:14:02] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"test","position":0,"id":"360598930553176065","type":4}
[02:14:02] [Fatal] [JDASocket]: Encountered an exception:
[02:14:02] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 360598930553176065
        at net.dv8tion.jda.handle.EntityBuilder.createGuildChannelPass(EntityBuilder.java:353)
        at net.dv8tion.jda.handle.EntityBuilder.createGuildFirstPass(EntityBuilder.java:231)
        at net.dv8tion.jda.handle.GuildJoinHandler.handleInternally(GuildJoinHandler.java:38)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:629)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at net.dv8tion.jda.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:705)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:243)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:937)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:696)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

[02:14:02] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"Voice","position":3,"id":"360599257209634817","type":4}
[02:14:02] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"gaming","position":1,"id":"360599589398773770","type":4}
[02:14:02] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"server","position":2,"id":"360607948969345035","type":4}
[02:14:02] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel. JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"General","position":0,"id":"360608087263936514","type":4}
[02:14:02] [Fatal] [JDA]: Received a channel for a guild that isn't a text or voice channel (ChannelPass). JSON: {"permission_overwrites":[],"nsfw":false,"parent_id":null,"name":"Voice","position":3,"id":"360599257209634817","type":4}
[02:14:02] [Fatal] [JDASocket]: Encountered an exception:
[02:14:02] [Fatal] [JDASocket]: java.lang.RuntimeException: Got permission_override for unknown channel with id: 360599257209634817
        at net.dv8tion.jda.handle.EntityBuilder.createGuildChannelPass(EntityBuilder.java:353)
        at net.dv8tion.jda.handle.EntityBuilder.createGuildFirstPass(EntityBuilder.java:231)
        at net.dv8tion.jda.handle.GuildJoinHandler.handleInternally(GuildJoinHandler.java:38)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:629)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at net.dv8tion.jda.requests.WebSocketClient.onBinaryMessage(WebSocketClient.java:705)
        at com.neovisionaries.ws.client.ListenerManager.callOnBinaryMessage(ListenerManager.java:368)
        at com.neovisionaries.ws.client.ReadingThread.callOnBinaryMessage(ReadingThread.java:243)
        at com.neovisionaries.ws.client.ReadingThread.handleBinaryFrame(ReadingThread.java:937)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:696)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

**Comment by lxqueen** [comment]
Can confirm the issue (running on Solus Linux with OpenJDK 8, if that helps).

**Comment by Jufoli** [comment]
Same issue here, but I know it was an JDA issue and it's fixed in JDA 3.3.1.
Please update the bot to use the new JDA so we can enjoy it again! 👍
You've done such nice work with this bot, please keep it up 🙃

**Comment by Darkside138** [comment]
I have some updated code locally. Just need to do some finalized testing
before sending it up. Hopefully, I'll have a new release up tonight. :)

**Comment by Jufoli** [comment]
Nice man! My mates already said I killed the bot 😢 ;)

**Comment by Darkside138** [comment]
The new release is out. Let me know if you have any issues.
