### ISSUE TITLE
Nullpointerexception

### ISSUE THREAD

**Issue by Foolius** [Darkside138/DiscordSoundboard#83]
I start the bot, everything looks good, then I visit the web-interface and I get this error:
```2017-10-27 16:55:08.529 ERROR 23029 --- [nio-8080-exec-9] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause

java.lang.NullPointerException: null
	at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.getUsersGuild(SoundPlayerImpl.java:505) ~[classes!/:2.1.1-beta]
	at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.setSoundPlayerVolume(SoundPlayerImpl.java:128) ~[classes!/:2.1.1-beta]
	at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl$$FastClassBySpringCGLIB$$28103730.invoke(<generated>) ~[classes!/:2.1.1-beta]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[classes!/:2.1.1-beta]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:669) ~[classes!/:2.1.1-beta]
	at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl$$EnhancerBySpringCGLIB$$ebdad442.setSoundPlayerVolume(<generated>) ~[classes!/:2.1.1-beta]
	at net.dirtydeeds.discordsoundboard.web.SoundboardRestController.setVolume(SoundboardRestController.java:128) ~[classes!/:2.1.1-beta]
	at sun.reflect.GeneratedMethodAccessor54.invoke(Unknown Source) ~[na:na]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[classes!/:2.1.1-beta]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872) ~[classes!/:2.1.1-beta]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661) ~[classes!/:2.1.1-beta]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[classes!/:2.1.1-beta]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[classes!/:2.1.1-beta]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[classes!/:2.1.1-beta]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [classes!/:2.1.1-beta]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478) [classes!/:2.1.1-beta]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [classes!/:2.1.1-beta]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80) [classes!/:2.1.1-beta]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [classes!/:2.1.1-beta]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342) [classes!/:2.1.1-beta]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799) [classes!/:2.1.1-beta]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [classes!/:2.1.1-beta]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) [classes!/:2.1.1-beta]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1457) [classes!/:2.1.1-beta]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [classes!/:2.1.1-beta]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_131]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [classes!/:2.1.1-beta]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
```
Also the bot doesn't go online in Discord. I authorized the bot and pasted the token into the app.properties and I gave his account in discord about all privileges there are to make sure this is not a problem.

**Comment by Darkside138** [comment]
That error means the bot isn't a member of any servers.
