### ISSUE TITLE
Windows: Can't run more than one bot.

### ISSUE THREAD

**Issue by Chrriiisss** [Darkside138/DiscordSoundboard#86]
I have two bots running to cover two servers. Once I updated both from a very old version I've only ever been able to run one bot at once because they're both set to run on port 8080 for the web interface.

Is there anyway to change the port for each bot?

Log:
2017-11-19 17:35:35.859  INFO 9312 --- [main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-11-19 17:35:35.869  INFO 9312 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Context refreshed
2017-11-19 17:35:35.890  INFO 9312 --- [main] d.s.w.p.DocumentationPluginsBootstrapper : Found 1 custom documentation plugin(s)
2017-11-19 17:35:35.902  INFO 9312 --- [main] s.d.s.w.s.ApiListingReferenceScanner     : Scanning for api listing references
2017-11-19 17:35:36.107 ERROR 9312 --- [main] o.a.coyote.http11.Http11NioProtocol      : Failed to start end point associated with ProtocolHandler ["http-nio-8080"]

java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_151]
	at sun.nio.ch.Net.bind(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.Net.bind(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[na:1.8.0_151]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210) ~[classes!/:2.1.1-beta]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:990) ~[classes!/:2.1.1-beta]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:635) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1022) [classes!/:2.1.1-beta]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [classes!/:2.1.1-beta]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) [classes!/:2.1.1-beta]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [classes!/:2.1.1-beta]
	at net.dirtydeeds.discordsoundboard.MainController.main(MainController.java:20) [classes!/:2.1.1-beta]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [DiscordSoundboard.jar:2.1.1-beta]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [DiscordSoundboard.jar:2.1.1-beta]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [DiscordSoundboard.jar:2.1.1-beta]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [DiscordSoundboard.jar:2.1.1-beta]

2017-11-19 17:35:36.108 ERROR 9312 --- [main] o.apache.catalina.core.StandardService   : Failed to start connector [Connector[HTTP/1.1-8080]]

org.apache.catalina.LifecycleException: Failed to start component [Connector[HTTP/1.1-8080]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.core.StandardService.addConnector(StandardService.java:225) ~[classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.addPreviouslyRemovedConnectors(TomcatEmbeddedServletContainer.java:250) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.tomcat.TomcatEmbeddedServletContainer.start(TomcatEmbeddedServletContainer.java:193) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.startEmbeddedServletContainer(EmbeddedWebApplicationContext.java:297) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:145) [classes!/:2.1.1-beta]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546) [classes!/:2.1.1-beta]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [classes!/:2.1.1-beta]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [classes!/:2.1.1-beta]
	at net.dirtydeeds.discordsoundboard.MainController.main(MainController.java:20) [classes!/:2.1.1-beta]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_151]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [DiscordSoundboard.jar:2.1.1-beta]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [DiscordSoundboard.jar:2.1.1-beta]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [DiscordSoundboard.jar:2.1.1-beta]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [DiscordSoundboard.jar:2.1.1-beta]
Caused by: org.apache.catalina.LifecycleException: service.getName(): "Tomcat";  Protocol handler start failed
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1029) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) ~[classes!/:2.1.1-beta]
	... 21 common frames omitted
Caused by: java.net.BindException: Address already in use: bind
	at sun.nio.ch.Net.bind0(Native Method) ~[na:1.8.0_151]
	at sun.nio.ch.Net.bind(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.Net.bind(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source) ~[na:1.8.0_151]
	at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source) ~[na:1.8.0_151]
	at org.apache.tomcat.util.net.NioEndpoint.bind(NioEndpoint.java:210) ~[classes!/:2.1.1-beta]
	at org.apache.tomcat.util.net.AbstractEndpoint.start(AbstractEndpoint.java:990) ~[classes!/:2.1.1-beta]
	at org.apache.coyote.AbstractProtocol.start(AbstractProtocol.java:635) ~[classes!/:2.1.1-beta]
	at org.apache.catalina.connector.Connector.startInternal(Connector.java:1022) ~[classes!/:2.1.1-beta]
	... 22 common frames omitted

2017-11-19 17:35:36.118  INFO 9312 --- [main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2017-11-19 17:35:36.206  INFO 9312 --- [main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-11-19 17:35:36.210 ERROR 9312 --- [main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

The Tomcat connector configured to listen on port 8080 failed to start. The port may already be in use or the connector may be misconfigured.

Action:

Verify the connector's configuration, identify and stop any process that's listening on port 8080, or configure this application to listen on another port.

**Comment by z1g** [comment]
you can add --server.port=8081 to the end of your startup command to listen on a different port. 

EG:

 java -jar DiscordSoundboard.jar >sb.log net.dirtydeeds.discordsoundboard.MainController --server.port=808
