### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by issueaccpost** [Darkside138/DiscordSoundboard#9]
hi, i am using linux(manjaro) and i am getting this error when i try to play a sound

[11:43:35] [Info] [ChatListener]: Attempting to play file: kackboon. Requested by Kurolux.
java.io.IOException: Resetting to invalid mark
        at java.io.BufferedInputStream.reset(BufferedInputStream.java:448)
        at net.sourceforge.jaad.spi.javasound.AACAudioFileReader.getAudioInputStream(AACAudioFileReader.java:129)
        at net.sourceforge.jaad.spi.javasound.AACAudioFileReader.getAudioInputStream(AACAudioFileReader.java:154)
        at javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1181)
        at net.dv8tion.jda.audio.player.FilePlayer.setAudioFile(FilePlayer.java:48)
        at net.dv8tion.jda.audio.player.FilePlayer.<init>(FilePlayer.java:36)
        at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.playFile(SoundPlayerImpl.java:434)
        at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.playFileForEvent(SoundPlayerImpl.java:182)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:205)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:177)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:65)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:36)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:551)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:298)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

**Comment by Darkside138** [comment]
Well, that's very odd. Have you run the bot on this version of Linux successfully before?

**Comment by lib2k** [comment]
What seems to be the problem here?
```
[00:21:28] [Info] [ChatListener]: Attempting to play file: hello. Requested by lib2k.
java.lang.RuntimeException: Could not get Private-channel for user: lib2k... Error: HTTPResponse[401: {"code": 0, "message": "401: Unauthorized"}]
        at net.dv8tion.jda.entities.impl.UserImpl.getPrivateChannel(UserImpl.java:124)
        at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.moveToUserIdsChannel(SoundPlayerImpl.java:353)
        at net.dirtydeeds.discordsoundboard.service.SoundPlayerImpl.playFileForEvent(SoundPlayerImpl.java:212)
        at net.dirtydeeds.discordsoundboard.ChatSoundBoardListener.onMessageReceived(ChatSoundBoardListener.java:214)
        at net.dv8tion.jda.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:184)
        at net.dv8tion.jda.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:64)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleDefaultMessage(MessageReceivedHandler.java:94)
        at net.dv8tion.jda.handle.MessageReceivedHandler.handleInternally(MessageReceivedHandler.java:50)
        at net.dv8tion.jda.handle.SocketHandler.handle(SocketHandler.java:38)
        at net.dv8tion.jda.requests.WebSocketClient.handleEvent(WebSocketClient.java:596)
        at net.dv8tion.jda.requests.WebSocketClient.onTextMessage(WebSocketClient.java:324)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:233)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:211)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:910)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:693)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:102)
        at com.neovisionaries.ws.client.ReadingThread.run(ReadingThread.java:61)

```

**Comment by z1g** [comment]
Not a dev, but my guess is you do not actually have a sound file named hello in the sounds folder, if so the bot would then send a DM to let you know that it cannot find said file, however at this time DM(direct message) seems to be broken as per issues #26 #27 #29

**Comment by lib2k** [comment]
There's one, and it's a actually an ordinary .mp3 file. In fact I don't receive any DMs from the bot at all. Neither a reaction to help commands like whatsoever. Only these error messages in the console.

**Comment by Darkside138** [comment]
The bot needs permissions to be able to send pms and modify messages in a channel. That should fix it.
