### ISSUE TITLE
Error in Playback

### ISSUE THREAD

**Issue by Fletchingguy** [Darkside138/DiscordSoundboard#98]
After entering a chat command or via the local host site, I receive the following:

2018-06-05 20:09:13.613  INFO 4552 --- [inWS-ReadThread] n.d.d.listeners.ChatSoundBoardListener   : Attempting to play file: thing2 1 times. Requested by Fletchingguy. ID: 397826291782516737
2018-06-05 20:09:13.752  INFO 4552 --- [inWS-ReadThread] n.d.jda.core.managers.AudioManager       : Audio System successfully setup!
2018-06-05 20:09:21.813  WARN 4552 --- [inWS-ReadThread] n.d.d.listeners.ChatSoundBoardListener   : Unable to delete message
2018-06-05 20:09:22.114 ERROR 4552 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of C:\Users\Gaming\Documents\DnD Modules\Soundboard\DiscordSoundboard-2.2.2-beta\sounds\thing2.m4a

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) [classes!/:2.2.2-beta]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.readFully(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/ByteBuffer;)V
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:84) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.standard.MpegStandardFileTrackProvider.provideFrames(MpegStandardFileTrackProvider.java:75) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:52) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioTrack.process(LocalAudioTrack.java:44) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90) ~[classes!/:2.2.2-beta]
        ... 4 common frames omitted

Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.readFully(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/ByteBuffer;)V
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:84)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.standard.MpegStandardFileTrackProvider.provideFrames(MpegStandardFileTrackProvider.java:75)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:52)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioTrack.process(LocalAudioTrack.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Darkside138** [comment]
Your bot needs permission to delete messages on the server. I think it's
called modify messages or something like that.

**Comment by Fletchingguy** [comment]
Thanks, that cleared up the "unable to delete messages" warning, but the playback error is persisting.
I've tried switching between musicPlayer and JDAPlayer in the app.properties file, but that hasn't helped. Is there a specific format the sound files need to be in?

2018-06-06 18:04:00.534  INFO 14628 --- [inWS-ReadThread] n.d.d.listeners.ChatSoundBoardListener   : Attempting to play file: thing2 1 times. Requested by Fletchingguy. ID: 397826291782516737
2018-06-06 18:04:00.632  INFO 14628 --- [inWS-ReadThread] n.d.jda.core.managers.AudioManager       : Audio System successfully setup!
2018-06-06 18:04:08.954 ERROR 14628 --- [back-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of C:\Users\Gaming\Documents\DnD Modules\Soundboard\DiscordSoundboard-2.2.2-beta\sounds\thing2.m4a

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:40) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:102) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348) [classes!/:2.2.2-beta]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.readFully(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/ByteBuffer;)V
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:84) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.standard.MpegStandardFileTrackProvider.provideFrames(MpegStandardFileTrackProvider.java:75) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:52) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioTrack.process(LocalAudioTrack.java:44) ~[classes!/:2.2.2-beta]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90) ~[classes!/:2.2.2-beta]
        ... 4 common frames omitted

Exception in thread "lava-daemon-pool-playback-1-thread-1" java.lang.NoSuchMethodError: org.apache.commons.io.IOUtils.readFully(Ljava/nio/channels/ReadableByteChannel;Ljava/nio/ByteBuffer;)V
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAacTrackConsumer.consume(MpegAacTrackConsumer.java:84)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.reader.standard.MpegStandardFileTrackProvider.provideFrames(MpegStandardFileTrackProvider.java:75)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:248)
        at com.sedmelluq.discord.lavaplayer.container.mpeg.MpegAudioTrack.process(MpegAudioTrack.java:52)
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
        at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioTrack.process(LocalAudioTrack.java:44)
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Jason-Terry** [comment]
I think this project is dead, I am having tons of issues, including this one.

**Comment by Darkside138** [comment]
I'm releasing an update soon. Hopefully will fix all these issues.
